// Auto-generated by scripts/upload-portfolio.mjs
// 238 images hosted on Cloudinary

export interface PortfolioPhoto {
  publicId: string;
}

export const PORTFOLIO_PHOTOS: PortfolioPhoto[] = [
  {
    "publicId": "miphotography/portfolio/IMG_0564"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0565"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0566"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0567"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0568"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0569"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0572"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0612"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0613"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0614"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0615"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0616"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0617"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0618"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0619"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0620"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0622"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0623"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0624"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0625"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0644"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0731"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0736"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0742"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0743"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0750"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0756"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0761"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0762"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0763"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0764"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0765"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0766"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0767"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0768"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0769"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0770"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0771"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0772"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0773"
  },
  {
    "publicId": "miphotography/portfolio/IMG_0774"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1184"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1191"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1300"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1301"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1302"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1303"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1304"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1305"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1319"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1320"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1321"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1322"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1323"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1324"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1328"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1333"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1369"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1370"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1371"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1372"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1588"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1589"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1590"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1591"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1592"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1605"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1606"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1613"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1614"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1615"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1616"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1628"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1629"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1630"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1631"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1636"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1637"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1655"
  },
  {
    "publicId": "miphotography/portfolio/IMG_1656"
  },
  {
    "publicId": "miphotography/portfolio/IMG_2186"
  },
  {
    "publicId": "miphotography/portfolio/IMG_2232"
  },
  {
    "publicId": "miphotography/portfolio/IMG_2233"
  },
  {
    "publicId": "miphotography/portfolio/IMG_2236"
  },
  {
    "publicId": "miphotography/portfolio/IMG_2237"
  },
  {
    "publicId": "miphotography/portfolio/IMG_2241"
  },
  {
    "publicId": "miphotography/portfolio/IMG_2242"
  },
  {
    "publicId": "miphotography/portfolio/IMG_2264"
  },
  {
    "publicId": "miphotography/portfolio/IMG_2271"
  },
  {
    "publicId": "miphotography/portfolio/IMG_3553"
  },
  {
    "publicId": "miphotography/portfolio/IMG_3554"
  },
  {
    "publicId": "miphotography/portfolio/IMG_3555"
  },
  {
    "publicId": "miphotography/portfolio/IMG_3556"
  },
  {
    "publicId": "miphotography/portfolio/IMG_3557"
  },
  {
    "publicId": "miphotography/portfolio/IMG_3558"
  },
  {
    "publicId": "miphotography/portfolio/IMG_3559"
  },
  {
    "publicId": "miphotography/portfolio/IMG_3560"
  },
  {
    "publicId": "miphotography/portfolio/IMG_3561"
  },
  {
    "publicId": "miphotography/portfolio/IMG_3562"
  },
  {
    "publicId": "miphotography/portfolio/IMG_3563"
  },
  {
    "publicId": "miphotography/portfolio/IMG_3782"
  },
  {
    "publicId": "miphotography/portfolio/IMG_3783"
  },
  {
    "publicId": "miphotography/portfolio/IMG_3784"
  },
  {
    "publicId": "miphotography/portfolio/IMG_3785"
  },
  {
    "publicId": "miphotography/portfolio/IMG_3786"
  },
  {
    "publicId": "miphotography/portfolio/IMG_3788"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4015"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4016"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4018"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4019"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4020"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4021"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4022"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4023"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4024"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4025"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4026"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4027"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4028"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4029"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4030"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4031"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4032"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4033"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4034"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4035"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4036"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4038"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4039"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4040"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4042"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4043"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4044"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4725"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4726"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4727"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4728"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4729"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4996"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4997"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4998"
  },
  {
    "publicId": "miphotography/portfolio/IMG_4999"
  },
  {
    "publicId": "miphotography/portfolio/IMG_5006"
  },
  {
    "publicId": "miphotography/portfolio/IMG_5010"
  },
  {
    "publicId": "miphotography/portfolio/IMG_5013"
  },
  {
    "publicId": "miphotography/portfolio/IMG_5336"
  },
  {
    "publicId": "miphotography/portfolio/IMG_5338"
  },
  {
    "publicId": "miphotography/portfolio/IMG_5339"
  },
  {
    "publicId": "miphotography/portfolio/IMG_5340"
  },
  {
    "publicId": "miphotography/portfolio/IMG_5341"
  },
  {
    "publicId": "miphotography/portfolio/IMG_5342"
  },
  {
    "publicId": "miphotography/portfolio/IMG_5343"
  },
  {
    "publicId": "miphotography/portfolio/IMG_5969"
  },
  {
    "publicId": "miphotography/portfolio/IMG_5970"
  },
  {
    "publicId": "miphotography/portfolio/IMG_5971"
  },
  {
    "publicId": "miphotography/portfolio/IMG_5972"
  },
  {
    "publicId": "miphotography/portfolio/IMG_5973"
  },
  {
    "publicId": "miphotography/portfolio/IMG_5974"
  },
  {
    "publicId": "miphotography/portfolio/IMG_5976"
  },
  {
    "publicId": "miphotography/portfolio/IMG_5977"
  },
  {
    "publicId": "miphotography/portfolio/IMG_5979"
  },
  {
    "publicId": "miphotography/portfolio/IMG_5980"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8361"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8363"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8364"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8365"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8939"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8940"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8941"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8942"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8943"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8944"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8945"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8946"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8947"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8948"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8949"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8950"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8951"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8952"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8953"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8954"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8955"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8956"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8957"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8958"
  },
  {
    "publicId": "miphotography/portfolio/IMG_8959"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9112"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9113"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9114"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9115"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9116"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9117"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9118"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9119"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9120"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9121"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9122"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9123"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9124"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9125"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9126"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9127"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9128"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9130"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9131"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9133"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9134"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9135"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9136"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9137"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9138"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9139"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9508"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9509"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9510"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9887"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9888"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9889"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9890"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9914"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9915"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9916"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9917"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9919"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9920"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9921"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9922"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9923"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9924"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9925"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9926"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9927"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9928"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9929"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9936"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9940"
  },
  {
    "publicId": "miphotography/portfolio/IMG_9941"
  }
];

/** First N photos for homepage preview */
export const PORTFOLIO_PREVIEW: PortfolioPhoto[] = PORTFOLIO_PHOTOS.slice(0, 12);
